name: CI

on:
  pull_request:
    branches: [main, develop]

  workflow_dispatch:

jobs:
  client:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [16, 18]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install package
        run: yarn install --frozen-lockfile

      - name: Run lint
        run: yarn lint && yarn format:check

      - name: Build test
        run: yarn run build
