name: CI

on:
  pull_request:
    branches: [main, develop]

  workflow_dispatch:

jobs:
  client:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [16, 18]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: cache-node-modules
        uses: actions/cache@v3
        id: node_modules_cache_id
        env:
          cache-name: cache-node-modules
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}

      - name: Install package
        if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        run: yarn install --frozen-lockfile

      - name: Run lint
        run: yarn lint && yarn format:check

      - name: Build test
        run: yarn run build
